version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - email_portfolio=${email_portfolio}
      - assistent_login=${assistent_login}
      - assistent_password=${assistent_password}
    networks:
      - my-network

networks:
  my-network:
    external: true